### ISSUE TITLE
Suggestion: UI changes.

### ISSUE THREAD

**Issue by jmonroynieto** [o02c/obsidian-tab-navigator#16]
I have fully integrated this into my workflow and it has freed me from a lot of friction, thank you.

A few observations for the roadmap in terms of UI.

1.  The prompt at the top (see screenshot) offers to create notes but when I type a new name it doesn't trigger note creation.
2.  The path under the title, although useful, I find it to be unactionable information for the most part because it will only show the filename in my vault given that I put most notes into the root directory. You could consider removing the filename from the path since the title and aliases already offer that information. The filename extension could potentially be a loss of info. In reality, it is not that useful in general (it's hidden from most users) and can be easily recuperated if the 3rd point of this list gets implemented.
3.  Using the icon to show what kind of page each tab is. This already works very well for modal tabs from other plugins. The example below has a Metadata menu tab for `"project"` represented by an open folder icon. Other icons could display viewer tabs (PDF) and canvas tabs. I think that would cover most tab classes and it would replace the information offered currently by the filename extension in case you implement the 2nd point in this list.
4. The word `tab` from the suggestion printout at the bottom of the modal has an important function and would be easier to understand at a glance should it be highlighted or colored in red or otherwise changed to stand out.  I would also change the wording to "close" since it closes the tab and does not delete the note.

I hope you consider a few of these, I mocked up the changes with a before-and-after to show how it would look.
The replacement icons from lucide.dev are:  Gallery-vertical-end, notebook-pen, and book-open-text.

![image1](https://github.com/o02c/obsidian-tab-navigator/assets/10119293/c836ebc6-fb91-4d6a-8136-9117fbd8ac65)

**Comment by o02c** [comment]
Thank you for your feedback.
It has been very helpful, since I rely on generative AI for coding and debugging the UI can be challenging. 

These changes have been reflected in the latest version (0.4.1).

1. Regarding note creation, this plugin is focused on tab navigation using fuzzy search. As a result, it shows suggestions even if there isn't an exact match, so implementing note creation isn't planned at the moment (though it might be added in the future). For now, I've updated the UI text to "Find a note ..." to reflect this.

2. Since I often organize my notes into separate folders, I added an option to toggle the display of file names. You can also toggle the visibility of the entire file path row.

3. I've switched from using custom SVGs to utilizing the SVGs provided by Obsidian's official set.

4. To improve clarity, I've highlighted the word "tab" and changed it to "close". However, instead of using red text, I've opted for a different form of emphasis. (I've replaced the string representation of tabs with Unicode icons.)

**Comment by jmonroynieto** [comment]
This is great! Thank you for being so responsive to my nitpicking! Making all key strokes as symbols  in the suggestion line looks great and is very readable!
Now with the wording change of the 4th point, both closing a note and exiting from the menu say `to close`. Please consider changing the quit option to `esc to exit`.

**Comment by o02c** [comment]
I agree that it can be confusing, so I have made the necessary adjustments. Thank you.
Now, the quit option is changed to "esc to exit" on latest version(0.4.2).
